# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ektam9931/flyrank-ml-week1/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task                                                  


 My lane is Content Performance Prediction. I frame it as a scoring (regression) task because I want to predict a numerical performance score for each content page. The prediction can help content teams identify which pages may need to be refreshed or optimized.

In [15]:
task_type = "scoring"
print("ML task type:", task_type)

ML task type: scoring

## 2. Target or proxy

I would predict the expected performance of a content page using a numerical performance score. The target would ideally come from an observed outcome such as measured traffic or engagement over a defined period. If that outcome is not directly available in the starter data, I would use a clearly defined proxy based on the available performance signals.

In [16]:
target = "content performance score"
print("Target:", target)

Target: content performance score

## 3. Success metric

I would use Mean Absolute Error (MAE) as the success metric. A lower MAE means the predicted performance score is closer to the observed outcome on average. I would consider a model useful if its MAE is lower than a simple baseline prediction.

In [17]:
success_metric = "MAE"
print("Success metric:", success_metric)
print("Lower MAE is better.")

Success metric: MAE
Lower MAE is better.

## 4. The unit of analysis, as a real dataframe

The unit of analysis is one content page. Each row represents one content item identified by a content_id, with SEO, traffic, engagement, freshness, and performance-related features. The dataframe contains 30,000 content-page records and 44 columns.

In [18]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [19]:
df.shape

(30000, 44)

In [20]:
df.columns.tolist()

['content_id',
 'client_id',
 'search_volume',
 'competition',
 'competition_level',
 'cpc',
 'content_type',
 'main_intent',
 'word_count',
 'char_count',
 'provider_used',
 'model_used',
 'impressions_90d',
 'clicks_90d',
 'pageviews_90d',
 'sessions_90d',
 'users_90d',
 'engaged_sessions_90d',
 'ai_sessions_90d',
 'scroll_events_90d',
 'days_with_impressions',
 'days_with_sessions',
 'impressions_last_30d',
 'clicks_last_30d',
 'sessions_last_30d',
 'impressions_prev_30d',
 'clicks_prev_30d',
 'sessions_prev_30d',
 'content_age_days',
 'age_tier',
 'age_tier_order',
 'days_since_last_update',
 'freshness_tier',
 'word_count_tier',
 'char_count_tier',
 'ctr',
 'avg_position',
 'engagement_rate',
 'scroll_rate',
 'ai_traffic_pct',
 'impression_tier',
 'position_tier',
 'trend_direction',
 'trend_pct']

In [21]:
df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [22]:
!pwd
!ls

/content/flyrank-ml-week1
AGENTS.md  DATA_USE.md	LICENSE    README.md	     SETUP.md	 work
CLAUDE.md  docs		notebooks  requirements.txt  skills
data	   GUIDE.md	outputs    scripts	     submission

In [23]:
!git clone https://github.com/ektam9931/flyrank-ml-week1.git

Cloning into 'flyrank-ml-week1'...
remote: Enumerating objects: 133, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 133 (delta 47), reused 85 (delta 28), pack-reused 0 (from 0)
Receiving objects: 100% (133/133), 1.85 MiB | 13.25 MiB/s, done.
Resolving deltas: 100% (47/47), done.

In [24]:
%cd /content/flyrank-ml-week1

/content/flyrank-ml-week1

In [25]:
!find data -type f

data/raw/content_refresh_anonymized.csv

## 5. Why ML beats a fixed rule here

A fixed rule would be too simple because content performance depends on several signals at the same time, including search demand, impressions, clicks, engagement, ranking position, content age, and recent trends. Different pages can have different combinations of these signals, so one threshold may not work well for all pages. ML can learn patterns across these measured features and provide decision-support for which content may need attention.

In [26]:
features = [
    "search_volume",
    "impressions_90d",
    "clicks_90d",
    "engagement_rate",
    "avg_position",
    "content_age_days",
    "trend_pct"
]

print("Number of performance signals:", len(features))
print("Signals used to support the ML framing:", features)

Number of performance signals: 7
Signals used to support the ML framing: ['search_volume', 'impressions_90d', 'clicks_90d', 'engagement_rate', 'avg_position', 'content_age_days', 'trend_pct']

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.